import { Elysia } from 'elysia'
import { staticPlugin } from '@elysiajs/static'
import { swagger } from '@elysiajs/swagger'
import os from 'os';

const osType = os.type();        // Returns "Windows_NT", "Darwin", or "Linux"
const osPlatform = os.platform(); // Returns "win32", "darwin", or "linux"

console.log(`Operating System: ${osType}`);

// =========================================================
// 📦 VIRTUAL FILE SYSTEM IMPORTS
// We explicitly embed the 3 predictable files generated by build.ts
// =========================================================
// =========================================================
// 📦 VIRTUAL FILE SYSTEM IMPORTS
// Use @ts-ignore to stop the IDE from looking for TypeScript types in these chunks.
// =========================================================
// @ts-ignore
import indexHtml from "../../public/dist/index.html" with { type: "file" };
// @ts-ignore
import indexJs from "../../public/dist/index.js" with { type: "file" };
// @ts-ignore
import indexCss from "../../public/dist/index.css" with { type: "file" };

const isProd = process.env.NODE_ENV === 'production' || Bun.argv.includes('--prod')
const publicFolder = isProd ? 'public/dist' : 'public'

console.log('\n' + '='.repeat(40))
console.log(`🚀 RUNNING IN ${isProd ? 'PRODUCTION' : 'DEVELOPMENT'} MODE`)
console.log('='.repeat(40) + '\n')

const app = new Elysia()
    .use(swagger())
    .onBeforeHandle(({ params, query, path, body }) => {
        console.log(`\n[${new Date().toLocaleTimeString()}] ${path}`);
        if (Object.keys(params || {}).length > 0) console.log('  Params:', params);
        if (Object.keys(query || {}).length > 0) console.log('  Query:', query);
        if (body) {
            // Log body keys but avoid logging large file buffers
            const bodyKeys = Object.keys(body as object);
            console.log('  Body:', bodyKeys.join(', '));
        }
    })
    // 1. Dynamic Uploads handler (Strictly reads disk, bypasses RAM cache)
    .get('/uploads/*', async ({ request }) => {
        const url = new URL(request.url);
        const file = Bun.file(`public${url.pathname}`);
        if (await file.exists()) return file;
        return new Response('Not Found', { status: 404, headers: { 'Content-Type': 'text/plain' } });
    })

    // 2. Safe Error Catching
    .onError(({ code, request }) => {
        const url = new URL(request.url);

        // A. Immediately kill missing APIs or Bun internal sockets
        if (url.pathname.startsWith('/api') || url.pathname.startsWith('/_bun')) {
            return new Response('Not Found', { status: 404, headers: { 'Content-Type': 'text/plain' } });
        }

        // B. DEV MODE SPA FALLBACK
        // The staticPlugin throws 'NOT_FOUND' for unknown routes like /App2.
        // We intercept it here and proxy to '/' so the bundler serves index.tsx
        if (!isProd && code === 'NOT_FOUND' && url.pathname !== '/') {
            url.pathname = '/';
            console.log(`[SPA Fallback] Proxying ${new URL(request.url).pathname} -> /`);
            return fetch(url.toString());
        }

        // C. Standard 404 for anything else that slips through
        if (code === 'NOT_FOUND') {
            return new Response('Not Found', { status: 404, headers: { 'Content-Type': 'text/plain' } });
        }
    });

// =========================================================
// 🚧 DEVELOPMENT MODE (Uses Elysia's Plugin to compile TSX on the fly)
// =========================================================
if (!isProd) {
    // In staticPlugin 1.4.9 they turned off html bundling by default!!
    app.use(await staticPlugin({ alwaysStatic: false, assets: publicFolder, prefix: '/', bunFullstack : true }));
}
// =========================================================
// 🚀 PRODUCTION MODE (Serves the 3 files directly from Binary RAM)
// =========================================================
else {
    console.log("📦 Embedded Files in Binary:");
    for (const file of Bun.embeddedFiles) {
        const blob = file as File;
        console.log(` - ${blob.name} (${blob.size} bytes)`);
        // e.g. "$bunfs/public/index.html"
    }

    // We cast the imports to strings to keep TypeScript happy
    app.get('/index.js', () => new Response(Bun.file(indexJs as unknown as string), { headers: { 'Content-Type': 'application/javascript' } }));
    app.get('/index.css', () => new Response(Bun.file(indexCss as unknown as string), { headers: { 'Content-Type': 'text/css' } }));

    // The Catch-All React Router Fallback
    app.get('/*', () => new Response(Bun.file(indexHtml as unknown as string), { headers: { 'Content-Type': 'text/html' } }));
}

// =========================================================
// 🔌 API ROUTES
// =========================================================
app.get('/api/ping', () => {
    return { status: 'success',  data: `Data from persistent Bun daemon! isProd=${isProd} ` + new Date().toLocaleString()+` ${osPlatform}`}
})

app.listen({
    port: process.env.PORT || 3000,
    // hostname: '0.0.0.0'
})
console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)